import type { PermissionCode, PersonaExperience } from "./access-control.types";
export type PersonaKey = "owner" | "director" | "teacher" | "student" | "parent" | "inactive";
const instructionalRead: PermissionCode[] = [
  "student_profiles.read",
  "assessment_history.read",
  "progress.read",
  "attendance.read",
  "study_plans.read",
];
export const personaPermissionMatrix: Record<Exclude<PersonaKey, "inactive">, PermissionCode[]> = {
  owner: [
    "students.read",
    "students.manage",
    "student_profiles.read",
    "student_profiles.manage",
    "assessment_history.read",
    "assessment_history.manage",
    "classes.read",
    "classes.manage",
    "attendance.read",
    "attendance.manage",
    "progress.read",
    "progress.manage",
    "analytics.read",
    "curriculum.read",
    "curriculum.manage",
    "study_plans.read",
    "study_plans.manage",
    "accounts.read",
    "accounts.manage",
    "roles.read",
    "roles.manage",
    "credentials.change_self",
    "credentials.force_reset",
    "audit.read",
  ],
  director: [
    "students.read",
    "students.manage",
    "student_profiles.read",
    "student_profiles.manage",
    "assessment_history.read",
    "assessment_history.manage",
    "classes.read",
    "classes.manage",
    "attendance.read",
    "attendance.manage",
    "progress.read",
    "progress.manage",
    "analytics.read",
    "curriculum.read",
    "curriculum.manage",
    "study_plans.read",
    "study_plans.manage",
    "accounts.read",
    "accounts.manage",
    "roles.read",
    "credentials.change_self",
  ],
  teacher: [
    "students.read",
    "student_profiles.read",
    "student_profiles.manage",
    "assessment_history.read",
    "assessment_history.manage",
    "classes.read",
    "attendance.read",
    "attendance.manage",
    "progress.read",
    "progress.manage",
    "curriculum.read",
    "study_plans.read",
    "study_plans.manage",
    "credentials.change_self",
  ],
  student: [...instructionalRead, "credentials.change_self"],
  parent: [...instructionalRead, "credentials.change_self"],
};
export const personaExperiences: Record<PersonaKey, PersonaExperience> = {
  owner: {
    profileId: "owner",
    label: "Owner",
    roleName: "Owner",
    scopeSummary: "全機構與角色治理",
    recommendedRoute: "/classes",
    recommendedLabel: "課程班級",
    primaryOperations: ["管理所有教務資料", "管理帳號與角色", "結業與封存班級"],
  },
  director: {
    profileId: "director",
    label: "主任",
    roleName: "主任",
    scopeSummary: "全機構日常營運",
    recommendedRoute: "/attendance",
    recommendedLabel: "出缺席",
    primaryOperations: ["管理學生與班級", "管理教材與點名", "查看分析與管理帳號"],
  },
  teacher: {
    profileId: "teacher",
    label: "老師",
    roleName: "老師",
    scopeSummary: "僅被指派班級",
    recommendedRoute: "/attendance",
    recommendedLabel: "出缺席",
    primaryOperations: ["班級點名", "登錄進度與成績", "查看授課學生"],
  },
  student: {
    profileId: "student",
    label: "學生",
    roleName: "學生",
    scopeSummary: "僅本人資料",
    recommendedRoute: "/students/stu-1",
    recommendedLabel: "我的學習紀錄",
    primaryOperations: ["查看個人進度", "查看考試紀錄", "查看修課計畫"],
  },
  parent: {
    profileId: "parent",
    label: "家長",
    roleName: "家長",
    scopeSummary: "僅已綁定孩子",
    recommendedRoute: "/students/stu-1",
    recommendedLabel: "孩子學習紀錄",
    primaryOperations: ["查看孩子進度", "查看考試紀錄", "查看修課計畫"],
  },
  inactive: {
    profileId: "inactive",
    label: "停用帳號",
    roleName: "停用帳號",
    scopeSummary: "無存取權",
    recommendedRoute: "/",
    recommendedLabel: "存取拒絕驗證",
    primaryOperations: ["驗證停用帳號無法讀取資料"],
  },
};
export const personaOptions = Object.values(personaExperiences);
